### ISSUE TITLE
Genome not available even if present in CopraRNA_available_organisms.txt

### ISSUE THREAD

**Issue by gprezza** [PatrickRWright/CopraRNA#33]
Hi there,

I'm trying to run CopraRNA locally, but I keep running into the problem that one genome I have in my input file is not available.

[https://www.ncbi.nlm.nih.gov/nuccore/NZ_CP040530](NZ_CP040530) is present in the prokaryotes.txt NCBI file and even in CopraRNA's _CopraRNA_available_organisms.txt_ file:
` grep "NZ_CP040530" ~/bin/CopraRNA/update_kegg2refseq/run/CopraRNA_available_organisms.txt`
gives:
`NZ_CP040530 NZ_CP040529 Bacteroides_thetaiotaomicron`

 However, when I run CopraRNA, I get the error:
`Error: 'NZ_CP040530' is not present in the availability list and is thus not compatible with CopraRNA.`

Am I missing something?

**Comment by PatrickRWright** [comment]
Hi there,

its been a long time since I last looked into CopraRNA but I assume you need to copy those files into the [`coprarna_aux`](https://github.com/PatrickRWright/CopraRNA/tree/master/coprarna_aux) directory in your local copy. The directory you are looking at in your `grep` statement is the example to run the update for the availability files. Once you have updated the files, you need to copy them over to coprarna_aux. I hope that makes sense and helps.

The README actually also explains this:
https://github.com/PatrickRWright/CopraRNA#update-coprarna-available-organisms

Cheers,
Patrick

**Comment by gprezza** [comment]
Oh you're right! I missed that part of the README. Thanks!

**Comment by PatrickRWright** [comment]
No worries. I glad it helped.
