### ISSUE TITLE
mRNAs are missing in CopraRNA's output file

### ISSUE THREAD

**Issue by ShaniCohen** [PatrickRWright/CopraRNA#37]
Hi,
I ran CopraRNA software to predict targets of the sRNA 'omrA', however, some mRNAs are not included in the output file (e.g.: gntp, glcd, hokd, yzgl...). 
Does it means that these mRNAs are predicted to have no interaction with 'omrA'? is this equivalent for setting a p-value of 1 for each of these mRNAs?

Thanks

**Comment by PatrickRWright** [comment]
Hi there,

its been a long time since I've looked into CopraRNA but off the top of my head I would say that these putative targets may not have enough homologs in the set of organisms that you have chosen for your analysis.

If you are interested in potential interactions between less conserved RNAs you could give IntaRNA a try. 

Cheers,
Patrick
